services:
  nginx:
    build:
      context: ./nginx
    container_name: bot_nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bot-network

  bot:
    build: .
    container_name: bot_app
    env_file: .env.local
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./dist:/app/
    networks:
      - bot-network

  db:
    image: mysql:8.0
    container_name: bot_db
    env_file: .env.local
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #command: --default-authentication-plugin=mysql_native_password
    networks:
      - bot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bot_PMA
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=0
      - PMA_ALLOW_NO_PASSWORD=0
    depends_on:
      - db
      - nginx
    networks:
      - bot-network

  certbot:
    image: certbot/certbot
    container_name: bot_certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  bot-network:
    driver: bridge

volumes:
  mysql-data:
