services:
  bot:
    build: .
    env_file: .env.local
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: mysql:8.0
    env_file: .env.local
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    #command: --default-authentication-plugin=mysql_native_password
    networks:
      - bot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:8081"
    environment:
      - PMA_HOST=db
      #- PMA_USER=${MYSQL_USER}
      #- PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ARBITRARY=0
      - PMA_ALLOW_NO_PASSWORD=0
    depends_on:
      - db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mysql-data:
